name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NOTIFY_API_KEY: ${{ secrets.NOTIFY_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install virtual environment with dev dependencies
        run: make install-dev
      - name: Running lint tests
        run: make lint
      - name: Running code tests
        run: make test
